from abc import ABC, abstractmethod
class NWPProvider(ABC):
    @abstractmethod
    async def get_forecast(self, **kwargs): ...
    @abstractmethod
    async def get_metadata(self): ...
    @abstractmethod
    async def get_available_variables(self): ...
    @abstractmethod
    async def get_forecast_runs(self): ...
