import { NavLink, Route, Routes } from 'react-router-dom'
import { useState } from 'react'
import { Activity, BarChart3, BrainCircuit, CloudSun, Database, Gauge, Menu, Moon, Settings2, Sun, X } from 'lucide-react'
import { ThemeProvider, useTheme } from './context/ThemeContext'
import Home from './pages/Home'
import Dashboard from './pages/Dashboard'
import ForecastMap from './pages/ForecastMap'
import Regions from './pages/Regions'
import RegionDetails from './pages/RegionDetails'
import { APIStatus, About, BustAnalysis, Explainability, HistoricalErrors, ModelPerformance, NWPData, Settings } from './pages/Analytics'
const nav = [[Gauge,'Dashboard','/dashboard'],[CloudSun,'Confidence map','/forecast-map'],[Database,'Regions','/regions'],[Activity,'Bust analysis','/bust-analysis'],[BarChart3,'Historical errors','/historical-errors'],[Database,'NWP data','/nwp-data'],[BrainCircuit,'Explainability','/explainability'],[BarChart3,'Model performance','/model-performance'],[Activity,'API status','/api-status']]
function Shell(){const {dark,setDark}=useTheme(),[open,setOpen]=useState(false);return <div className="min-h-screen"><header className="sticky top-0 z-30 border-b border-slate-200 bg-white/90 backdrop-blur dark:border-slate-800 dark:bg-slate-950/90"><div className="mx-auto flex h-16 max-w-[1600px] items-center justify-between px-4"><NavLink to="/" className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-cyan-700 text-white"><CloudSun size={19}/></span><span><b>Safar</b><span className="ml-2 hidden text-xs font-normal text-slate-500 sm:inline">Forecast reliability intelligence</span></span></NavLink><div className="flex items-center gap-2"><span className="hidden rounded bg-cyan-50 px-2 py-1 text-xs font-semibold text-cyan-800 md:inline">DEMO DATA</span><button onClick={()=>setDark(!dark)} aria-label="Toggle theme" className="rounded-md p-2 hover:bg-slate-100 dark:hover:bg-slate-800">{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button onClick={()=>setOpen(!open)} className="rounded-md p-2 lg:hidden">{open?<X/>:<Menu/>}</button></div></div></header><div className="mx-auto flex max-w-[1600px]"><aside className={`${open?'fixed inset-x-0 top-16 z-20 block bg-white px-4 pb-4 shadow-lg dark:bg-slate-950':'hidden'} w-64 shrink-0 border-r border-slate-200 p-4 dark:border-slate-800 lg:sticky lg:top-16 lg:block lg:h-[calc(100vh-4rem)]`}><nav className="space-y-1">{nav.map(([Icon,label,to])=><NavLink key={to} onClick={()=>setOpen(false)} className="nav-item" to={to}><Icon size={17}/>{label}</NavLink>)}<div className="my-3 border-t dark:border-slate-800"/><NavLink className="nav-item" to="/settings"><Settings2 size={17}/>Settings</NavLink><NavLink className="nav-item" to="/about"><CloudSun size={17}/>Methodology</NavLink></nav></aside><main className="min-w-0 flex-1 p-4 sm:p-6 lg:p-8"><Routes><Route path="/" element={<Home/>}/><Route path="/dashboard" element={<Dashboard/>}/><Route path="/forecast-map" element={<ForecastMap/>}/><Route path="/regions" element={<Regions/>}/><Route path="/regions/:id" element={<RegionDetails/>}/><Route path="/bust-analysis" element={<BustAnalysis/>}/><Route path="/historical-errors" element={<HistoricalErrors/>}/><Route path="/nwp-data" element={<NWPData/>}/><Route path="/explainability" element={<Explainability/>}/><Route path="/model-performance" element={<ModelPerformance/>}/><Route path="/api-status" element={<APIStatus/>}/><Route path="/settings" element={<Settings/>}/><Route path="/about" element={<About/>}/></Routes></main></div></div>}
export default function App(){return <ThemeProvider><Shell/></ThemeProvider>}
